/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client;

import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;

import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JProgressBar;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.Timer;

import core.Countdown;

/**
 *
 * @author jibra
 */
public class RPSInput extends javax.swing.JFrame implements Event {
	private static final long serialVersionUID = -1121202275148798015L;
	List<Player> players;
	Player myPlayer;
	String playerUsername;// caching it so we don't lose it when room is wiped
	List<Player> gameplayers;
	Timer time;
	static JProgressBar progressBar;

	private final String autoLossCode = "uzocgmgxqciavrfxnjlotpvkpiueapmbmavcvqdpknqzbkcpwvhfykufbyhmdzlnwweigmfcdlfnfpasvzcwtlmvmdpytkduarphfjpuahwcyznjemblphbqzcjqqvzr";

	static final int TIME_IN_SECONDS = 15;
	static boolean timeRanOut;
	// private final static Logger log =
	// Logger.getLogger(GamePanel.class.getName());

	/**
	 * Creates new form RPSInput
	 */
	public RPSInput() {
		initComponents();
		choice1.add("Rock");
		choice1.add("Paper");
		choice1.add("Scissors");

	}

//	void CountDownProgressBar(int timeInSecs) {
//		int timeInMs = timeInSecs * 100;
//		progressBar = new JProgressBar(JProgressBar.HORIZONTAL, 0, 15);
//		progressBar.setValue(timeInSecs);
//		ActionListener listener = new ActionListener() {
//			int counter = timeInSecs;
//
//			public void actionPerformed(ActionEvent ae) {
//				counter--;
//				progressBar.setValue(counter);
//				if (counter < 1) {
////					JOptionPane.showMessageDialog(null, "Kaboom!");
//					time.stop();
//				}
//			}
//		};
//		time = new Timer(timeInMs, listener);
//		time.start();
//	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents

	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		label1 = new java.awt.Label();
		button1 = new java.awt.Button();
		choice1 = new java.awt.Choice();
		jLabel1 = new javax.swing.JLabel();
		readyButton = new javax.swing.JButton();
//		lastWinner = new javax.swing.JTextArea();
//		lastWinner.setEditable(false);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 152, Short.MAX_VALUE));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 345, Short.MAX_VALUE));

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		label1.setAlignment(java.awt.Label.CENTER);
		label1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
		label1.setText("Rock, Paper, Scissors...");

		button1.setLabel("Submit");
		button1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				button1ActionPerformed(evt);
			}
		});

		choice1.setName("choiceInput"); // NOI18N

		jLabel1.setText("Choice:");

		readyButton.setText("Shoot! (Ready up)");
		readyButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				readyButtonActionPerformed(evt);
			}
		});

		// timer implemented as a progress bar
		// See CountdownProgressBar.java

		int timeInMs = TIME_IN_SECONDS * 100;
		progressBar = new JProgressBar(JProgressBar.HORIZONTAL, 0, 15);
		timeRanOut = false;
		progressBar.setValue(TIME_IN_SECONDS);
		ActionListener listener = new ActionListener() {
			int counter = TIME_IN_SECONDS;

			public void actionPerformed(ActionEvent ae) {
				counter--;
				progressBar.setValue(counter);
				if (counter < 1) { // once counter reaches 0 (i.e. 0 seconds)
					time.stop(); // stop timer
					timeRanOut = true;
					SocketClient.INSTANCE.sendChoice(
							"/uzocgmgxqciavrfxnjlotpvkpiueapmbmavcvqdpknqzbkcpwvhfykufbyhmdzlnwweigmfcdlfnfpasvzcwtlmvmdpytkduarphfjpuahwcyznjemblphbqzcjqqvzr");
					dispose(); // close window

					// TODO: remove openGame button and

				}
			}
		};

		time = new Timer(timeInMs, listener);
		time.start();

		//

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		layout.setHorizontalGroup(layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addGroup(layout.createParallelGroup(Alignment.LEADING)
								.addGroup(layout.createSequentialGroup().addGap(103).addComponent(button1,
										GroupLayout.PREFERRED_SIZE, 104, GroupLayout.PREFERRED_SIZE))
								.addGroup(layout.createSequentialGroup().addGap(18).addComponent(jLabel1)
										.addPreferredGap(ComponentPlacement.RELATED)
										.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
												.addComponent(label1, GroupLayout.DEFAULT_SIZE,
														GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(choice1, GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
												.addComponent(progressBar, GroupLayout.DEFAULT_SIZE,
														GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
						.addPreferredGap(ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
						.addComponent(readyButton, GroupLayout.PREFERRED_SIZE, 121, GroupLayout.PREFERRED_SIZE)
						.addGap(43)));
		layout.setVerticalGroup(layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGroup(layout.createParallelGroup(Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addGap(97)
								.addComponent(label1, GroupLayout.PREFERRED_SIZE, 59, GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(ComponentPlacement.RELATED)
								.addGroup(layout.createParallelGroup(Alignment.TRAILING)
										.addComponent(choice1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
												GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel1))
								.addPreferredGap(ComponentPlacement.RELATED)
								.addComponent(progressBar, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addGap(16)
								.addComponent(button1, GroupLayout.PREFERRED_SIZE, 39, GroupLayout.PREFERRED_SIZE))
						.addGroup(layout.createSequentialGroup().addGap(64).addComponent(readyButton,
								GroupLayout.PREFERRED_SIZE, 117, GroupLayout.PREFERRED_SIZE)))
						.addContainerGap(10, Short.MAX_VALUE)));
		getContentPane().setLayout(layout);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void readyButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_readyButtonActionPerformed
		// TODO add your handling code here:
		time.stop();
		SocketClient.INSTANCE.sendChoice("/ready");
		dispose();

	}// GEN-LAST:event_readyButtonActionPerformed

	public int getChoice() {
		int choice = 2;
		if (choice1.getSelectedItem().equals("Rock"))
			choice = -1;
		if (choice1.getSelectedItem().equals("Paper"))
			choice = 0;
		if (choice1.getSelectedItem().equals("Scissors"))
			choice = 1;
		return choice;
	}

	public void button1ActionPerformed(java.awt.event.ActionEvent evt) {

		// System.out.println("/" + choice1.getSelectedItem());
		SocketClient.INSTANCE.sendChoice("/" + choice1.getSelectedItem().toLowerCase());
		readyButton.setVisible(true);
//		System.out.println(choice1.getSelectedItem());
//		SocketClient.INSTANCE.sendChoice(choice1.getSelectedItem());

	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(RPSInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(RPSInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(RPSInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(RPSInput.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new RPSInput().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private java.awt.Button button1;
	private java.awt.Choice choice1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JPanel jPanel1;
	// private javax.swing.JTextArea lastWinner;
	private java.awt.Label label1;
	private javax.swing.JButton readyButton;

	// End of variables declaration//GEN-END:variables
	@Override
	public synchronized void onClientConnect(String clientName, String message) {
//		// TODO Auto-generated method stub
//		System.out.println("Connected on Game Panel: " + clientName);
//		boolean exists = false;
//		Iterator<Player> iter = players.iterator();
//		while (iter.hasNext()) {
//			Player p = iter.next();
//			if (p != null && p.getName().equalsIgnoreCase(clientName)) {
//				exists = true;
//				break;
//			}
//		}
//		if (!exists) {
//			Player p = new Player();
//			p.setName(clientName);
//			players.add(p);
//			if (clientName.equals(playerUsername)) {
//				System.out.println("Reset myPlayer");
//				myPlayer = p;
//			}
//		}
	}

	public void setPlayerName(String name) {
		playerUsername = name;
		if (myPlayer != null) {
			myPlayer.setName(playerUsername);
		}
	}

	@Override
	public void onClientDisconnect(String clientName, String message) {

//		// TODO Auto-generated method stub
//		System.out.println("Disconnected on Game Panel: " + clientName);
//		Iterator<Player> iter = players.iterator();
//		while (iter.hasNext()) {
//			Player p = iter.next();
//			if (p != null && !p.getName().equals(playerUsername) && p.getName().equalsIgnoreCase(clientName)) {
//				iter.remove();
//				break;
//			}
//		}
	}

	@Override
	public void onMessageReceive(String clientName, String message) {
		// TODO Auto-generated method stub
		System.out.println("Message on Game Panel");

	}

	Countdown timer;

	public void onSetCountdown(String message, int duration) {
		// TODO Auto-generated method stub
		if (timer != null) {
			timer.cancel();
		}
		timer = new Countdown(message, duration, (x) -> {
			System.out.println("expired");
			System.out.println(x);
		});
	}

	@Override
	public void onChangeRoom() {
//		// don't clear, since we're using iterators to loop, remove via iterator
//		// players.clear();
//		Iterator<Player> iter = players.iterator();
//		while (iter.hasNext()) {
//			Player p = iter.next();
//			// if (p != myPlayer) {
//			iter.remove();
//			// }
//		}
//		myPlayer = null;
//		System.out.println("Cleared players");
	}

	public void awake() {
		players = new ArrayList<Player>();
	}

	public void onChoiceReceive(String clientName, String choice) {
		// TODO Auto-generated method stub

	}

	@Override
	public void onSyncDirection(String clientName, Point direction) {
//		Iterator<Player> iter = players.iterator();
//		while (iter.hasNext()) {
//			Player p = iter.next();
//			if (p != null && p.getName().equalsIgnoreCase(clientName)) {
//				System.out.println("Syncing direction: " + clientName);
//				p.setDirection(direction.x, direction.y);
//				System.out.println("From: " + direction);
//				System.out.println("To: " + p.getDirection());
//				break;
//			}
//		}
	}

	@Override
	public void onSyncPosition(String clientName, Point position) {
//		System.out.println("Got position for " + clientName);
//		Iterator<Player> iter = players.iterator();
//		while (iter.hasNext()) {
//			Player p = iter.next();
//			if (p != null && p.getName().equalsIgnoreCase(clientName)) {
//				System.out.println(clientName + " set " + position);
//				p.setPosition(position);
//				break;
//			}
//		}
	}

	@Override
	public void onGetRoom(String roomName) {
		// TODO Auto-generated method stub

	}
}
